#!/bin/bash
#
# This script requires lcov and dirname
#

TESTS="\
test_peer \
test_util"

function err() {
    echo "*** ERROR!" $1
    exit 1
}

# Check the required tools
which lcov >> /dev/null || err "Please install lcov"
which dirname >> /dev/null || err "Please install dirname"

# LCOV 1.10 has branch coverage disabled per default
# Previous versions didn't have the --rc option
if  [ ! -z "$(lcov --help | grep ' --rc ')" ] ; then
    LCOV_OPT="--rc lcov_branch_coverage=1"
    GENHTML_OPT="--branch-coverage"
fi

pushd `dirname $0` > /dev/null
COV_DIR="$PWD"
pushd .. > /dev/null
TEST_DIR="$PWD"
pushd .. > /dev/null
TOP_DIR="$PWD"
popd > /dev/null
popd > /dev/null
popd > /dev/null

make -C "$TOP_DIR" clean
for t in $TESTS ; do
    pushd "$TEST_DIR/$t"
    make -C "$TEST_DIR/$t" clean coverage || exit 1
    build/coverage/$t || exit 1
    popd
done

BASE_DIR="$TOP_DIR"
COV_FILE="$COV_DIR/libgiorpc.gcov"
rm -f "$GCOV_FILE"
lcov $LCOV_OPT -c -d "$TOP_DIR/build/coverage" -b "$BASE_DIR" -o "$COV_FILE" || exit 1
lcov $LCOV_OPT -e "$COV_FILE" "$BASE_DIR/*" -o "$COV_FILE" || exit 1
genhtml $GENHTML_OPT "$COV_FILE" -t "libgiorpc" --output-directory "$COV_DIR/report" || exit 1
